import os
import sys
import logging
from dotenv import load_dotenv

from fetch_sectors import get_idx_total, get_ihsg, get_top_changes
from format_brief import normalize_data, format_data_for_ai, generate_fallback_message
from summarize_ai import summarize_market_data
from send_telegram import send_telegram_message

# Ensure logs directory exists if running locally (ignored by git)
os.makedirs("logs", exist_ok=True)

# Configure logging
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(name)s: %(message)s",
    handlers=[
        logging.StreamHandler(sys.stdout),
        logging.FileHandler("logs/daily_brief.log", encoding="utf-8")
    ]
)

logger = logging.getLogger(__name__)

def main():
    # Load env vars for local development (will be ignored in GitHub Actions if not present)
    load_dotenv()
    
    logger.info("Starting Sectors Daily Brief workflow...")
    
    try:
        # Step 1: Fetch Data
        logger.info("Fetching data from Sectors API...")
        idx_total = get_idx_total()
        ihsg = get_ihsg()
        top_changes = get_top_changes()
        
        # Step 2: Normalize Data
        normalized = normalize_data(idx_total, ihsg, top_changes)
        
        # Step 3: Summarize via AI
        formatted_for_ai = format_data_for_ai(normalized)
        ai_summary = summarize_market_data(formatted_for_ai)
        
        # Step 4: Formatting Message
        if ai_summary:
            logger.info("Using AI-generated summary.")
            final_message = f"🤖 **AI Market Brief**\n\n{ai_summary}\n\n_Generated by Sectors Daily Brief_"
        else:
            logger.warning("AI summary failed or was not configured. Using fallback template.")
            final_message = generate_fallback_message(normalized)
            
        # Step 5: Send to Telegram
        send_telegram_message(final_message)
        
        logger.info("Workflow completed successfully.")
        
    except Exception as e:
        logger.exception("A critical error occurred in the workflow.")
        # Attempt to send error alert to telegram if possible
        try:
            error_msg = f"⚠️ **Sectors Daily Brief Alert**\n\nFailed to run morning brief workflow. Check GitHub Actions logs.\n\nError: `{str(e)}`"
            send_telegram_message(error_msg)
        except Exception:
            pass
        sys.exit(1)

if __name__ == "__main__":
    main()
